### ISSUE TITLE
Multiple identifiers aka Composite keys don't group correctly

### ISSUE THREAD

**Issue by NunoRamos1994** [Dolfik1/Mappy#5]
In the file MappingContext.cs you have change the group logic, in line  240 you use the method GetHashCode of IdentifierComparer.cs, on that method on line 83 the HashCode.CombineHashCodes(hc, hashCode) return value isn't assigned to the hashCode variable.

**Comment by Dolfik1** [comment]
Thank you for issue. I've fixed composite keys bug and also possible hash collisions bug.
