### ISSUE TITLE
Property of SortedSet type can not be mapped

### ISSUE THREAD

**Issue by Alexcei88** [Dolfik1/Mappy#6]
Suppose, there is an object with SortedSet property
 
```
class  Customer
{
    public int CustomerId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public SortedSet<Order> Orders { get; set; }
}
```
If I try to map it, I get the following error

> Message: 
>     System.ArgumentException : Argument types do not match
>   Stack Trace: 
>     Expression.Bind(MemberInfo member, Expression expression)

In my project it is important to have SortedSet property, I would not like to change to other collection types. I propose to add supporting of objects contained such collection.

I created a PR #7  to fix this issue

**Comment by Dolfik1** [comment]
Thank you for MR. I will update NuGet version soon
